'use client';

const PROJECTS_KEY = 'codoptic:projects:v1';
const ACTIVE_PROJECT_ID_KEY = 'codoptic:active-project:v1';
const PROJECTS_UPDATED_AT_KEY = 'codoptic:projects-updated-at:v1';

export interface LayerDiagram {
  name: string;
  description: string;
  dsl: string;
}

export interface MultiLayerOutput {
  /** High-level diagram covering all layers */
  overview: LayerDiagram;
  /** One sub-diagram per layer */
  layers: LayerDiagram[];
  generatedAt: number;
}

export interface StoredProject {
  id: string;
  name: string;
  dsl: string;
  createdAt: number;
  /** Optional Instruction Mode guide generated alongside the diagram */
  instructionMarkdown?: string;
  /** Present when the project was generated by the Multi-Layer pipeline */
  multiLayer?: MultiLayerOutput;
}

export function getMultiLayerDsl(
  multiLayer: MultiLayerOutput,
  activeLayer: string,
): string | undefined {
  if (activeLayer === 'overview') return multiLayer.overview.dsl;
  return multiLayer.layers.find((layer) => layer.name === activeLayer)?.dsl;
}

export function updateMultiLayerDsl(
  multiLayer: MultiLayerOutput,
  activeLayer: string,
  dsl: string,
): MultiLayerOutput {
  if (activeLayer === 'overview') {
    return {
      ...multiLayer,
      overview: { ...multiLayer.overview, dsl },
    };
  }

  const hasActiveLayer = multiLayer.layers.some((layer) => layer.name === activeLayer);
  if (!hasActiveLayer) return multiLayer;

  return {
    ...multiLayer,
    layers: multiLayer.layers.map((layer) =>
      layer.name === activeLayer ? { ...layer, dsl } : layer,
    ),
  };
}

export function applyProjectDsl(
  project: StoredProject,
  dsl: string,
  activeLayer: string,
): StoredProject {
  if (!project.multiLayer) return { ...project, dsl };

  const multiLayer = updateMultiLayerDsl(project.multiLayer, activeLayer, dsl);
  return {
    ...project,
    dsl: activeLayer === 'overview' ? dsl : multiLayer.overview.dsl,
    multiLayer,
  };
}

function canUseLocalStorage(): boolean {
  return typeof window !== 'undefined' && typeof window.localStorage !== 'undefined';
}

let memoryProjects: StoredProject[] | null = null;
let memoryUpdatedAt = 0;

function sanitizeProjects(value: unknown): StoredProject[] {
  if (!Array.isArray(value)) return [];
  return value.filter(
    (p): p is StoredProject =>
      typeof p === 'object' &&
      p !== null &&
      typeof p.id === 'string' &&
      typeof p.name === 'string' &&
      typeof p.dsl === 'string' &&
      typeof p.createdAt === 'number',
  );
}

function readLocalStorageProjects(): StoredProject[] {
  if (!canUseLocalStorage()) return [];
  try {
    const raw = window.localStorage.getItem(PROJECTS_KEY);
    if (!raw) return [];
    return sanitizeProjects(JSON.parse(raw));
  } catch {
    return [];
  }
}

function tryWriteLocalStorage(projects: StoredProject[], updatedAt: number): void {
  if (!canUseLocalStorage()) return;
  try {
    window.localStorage.setItem(PROJECTS_KEY, JSON.stringify(projects));
    window.localStorage.setItem(PROJECTS_UPDATED_AT_KEY, String(updatedAt));
  } catch {
    // QuotaExceededError — IndexedDB remains the durable catalog.
  }
}

function persistCatalog(projects: StoredProject[], updatedAt: number): void {
  const activeProjectId = readActiveProjectId();
  void import('../cache/draftCache')
    .then((mod) =>
      mod.saveProjectCatalog({
        projects,
        activeProjectId,
        updatedAt,
      }),
    )
    .catch(() => undefined);
}

export function getProjectsUpdatedAt(): number {
  if (memoryUpdatedAt) return memoryUpdatedAt;
  if (!canUseLocalStorage()) return 0;
  const raw = window.localStorage.getItem(PROJECTS_UPDATED_AT_KEY);
  const parsed = raw ? Number(raw) : 0;
  return Number.isFinite(parsed) ? parsed : 0;
}

export function hydrateProjectsFromCatalog(projects: StoredProject[], updatedAt: number): void {
  memoryProjects = projects;
  memoryUpdatedAt = updatedAt;
  tryWriteLocalStorage(projects, updatedAt);
}

export function readStoredProjects(): StoredProject[] {
  if (memoryProjects) return memoryProjects;
  const stored = readLocalStorageProjects();
  memoryProjects = stored;
  return stored;
}

export function writeStoredProjects(projects: StoredProject[]): void {
  const updatedAt = Date.now();
  memoryProjects = projects;
  memoryUpdatedAt = updatedAt;
  tryWriteLocalStorage(projects, updatedAt);
  persistCatalog(projects, updatedAt);
}

export async function writeStoredProjectsDurable(projects: StoredProject[]): Promise<void> {
  const updatedAt = Date.now();
  memoryProjects = projects;
  memoryUpdatedAt = updatedAt;
  tryWriteLocalStorage(projects, updatedAt);
  try {
    const { saveProjectCatalog } = await import('../cache/draftCache');
    await saveProjectCatalog({
      projects,
      activeProjectId: readActiveProjectId(),
      updatedAt,
    });
  } catch {
    // IndexedDB may be unavailable in tests or private mode.
  }
}

function getNextAutoProjectName(projects: StoredProject[]): string {
  const used = new Set<number>();

  for (const project of projects) {
    const match = /^project(\d+)$/i.exec(project.name.trim());
    if (!match) continue;
    used.add(Number(match[1]));
  }

  let next = 1;
  while (used.has(next)) next++;
  return `project${next}`;
}

function getUniqueProjectName(projects: StoredProject[], name: string): string {
  const existingNames = new Set(projects.map((p) => p.name));
  let uniqueName = name;
  let counter = 2;
  while (existingNames.has(uniqueName)) {
    uniqueName = `${name} ${counter}`;
    counter++;
  }
  return uniqueName;
}

export function addStoredProject(
  name: string,
  dsl: string,
  multiLayer?: MultiLayerOutput,
  instructionMarkdown?: string,
): StoredProject {
  const projects = readStoredProjects();
  const trimmedName = name.trim();
  const uniqueName = /^project\d+$/i.test(trimmedName)
    ? getNextAutoProjectName(projects)
    : getUniqueProjectName(projects, trimmedName);

  const project: StoredProject = {
    id: `proj-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
    name: uniqueName,
    dsl,
    createdAt: Date.now(),
    ...(multiLayer ? { multiLayer } : {}),
    ...(instructionMarkdown ? { instructionMarkdown } : {}),
  };
  writeStoredProjects([project, ...projects]);
  return project;
}

export function renameStoredProject(id: string, name: string): void {
  const projects = readStoredProjects().map((p) => (p.id === id ? { ...p, name } : p));
  writeStoredProjects(projects);
}

export function getNextProjectName(): string {
  return getNextAutoProjectName(readStoredProjects());
}

export function removeStoredProject(id: string): void {
  const projects = readStoredProjects().filter((p) => p.id !== id);
  writeStoredProjects(projects);
}

export function updateStoredProject(id: string, dsl: string, activeLayer = 'overview'): void {
  const projects = readStoredProjects().map((p) =>
    p.id === id ? applyProjectDsl(p, dsl, activeLayer) : p,
  );
  writeStoredProjects(projects);
}

export function readActiveProjectId(): string | null {
  if (!canUseLocalStorage()) return null;
  return window.localStorage.getItem(ACTIVE_PROJECT_ID_KEY);
}

export function writeActiveProjectId(id: string | null): void {
  if (!canUseLocalStorage()) return;
  if (id === null) {
    window.localStorage.removeItem(ACTIVE_PROJECT_ID_KEY);
  } else {
    window.localStorage.setItem(ACTIVE_PROJECT_ID_KEY, id);
  }
}
