'use client';

const PROJECTS_KEY = 'codoptic:projects:v1';
const ACTIVE_PROJECT_ID_KEY = 'codoptic:active-project:v1';

export interface LayerDiagram {
  name: string;
  description: string;
  dsl: string;
}

export interface MultiLayerOutput {
  /** High-level diagram covering all layers */
  overview: LayerDiagram;
  /** One sub-diagram per layer */
  layers: LayerDiagram[];
  generatedAt: number;
}

export interface StoredProject {
  id: string;
  name: string;
  dsl: string;
  createdAt: number;
  /** Optional Instruction Mode guide generated alongside the diagram */
  instructionMarkdown?: string;
  /** Present when the project was generated by the Multi-Layer pipeline */
  multiLayer?: MultiLayerOutput;
}

export function getMultiLayerDsl(
  multiLayer: MultiLayerOutput,
  activeLayer: string,
): string | undefined {
  if (activeLayer === 'overview') return multiLayer.overview.dsl;
  return multiLayer.layers.find((layer) => layer.name === activeLayer)?.dsl;
}

export function updateMultiLayerDsl(
  multiLayer: MultiLayerOutput,
  activeLayer: string,
  dsl: string,
): MultiLayerOutput {
  if (activeLayer === 'overview') {
    return {
      ...multiLayer,
      overview: { ...multiLayer.overview, dsl },
    };
  }

  const hasActiveLayer = multiLayer.layers.some((layer) => layer.name === activeLayer);
  if (!hasActiveLayer) return multiLayer;

  return {
    ...multiLayer,
    layers: multiLayer.layers.map((layer) =>
      layer.name === activeLayer ? { ...layer, dsl } : layer,
    ),
  };
}

export function applyProjectDsl(
  project: StoredProject,
  dsl: string,
  activeLayer: string,
): StoredProject {
  if (!project.multiLayer) return { ...project, dsl };

  const multiLayer = updateMultiLayerDsl(project.multiLayer, activeLayer, dsl);
  return {
    ...project,
    dsl: activeLayer === 'overview' ? dsl : multiLayer.overview.dsl,
    multiLayer,
  };
}

function canUseLocalStorage(): boolean {
  return typeof window !== 'undefined' && typeof window.localStorage !== 'undefined';
}

export function readStoredProjects(): StoredProject[] {
  if (!canUseLocalStorage()) return [];
  try {
    const raw = window.localStorage.getItem(PROJECTS_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    if (!Array.isArray(parsed)) return [];
    return parsed.filter(
      (p): p is StoredProject =>
        typeof p === 'object' &&
        p !== null &&
        typeof p.id === 'string' &&
        typeof p.name === 'string' &&
        typeof p.dsl === 'string' &&
        typeof p.createdAt === 'number',
    );
  } catch {
    return [];
  }
}

export function writeStoredProjects(projects: StoredProject[]): void {
  if (!canUseLocalStorage()) return;
  window.localStorage.setItem(PROJECTS_KEY, JSON.stringify(projects));
}

function getNextAutoProjectName(projects: StoredProject[]): string {
  const used = new Set<number>();

  for (const project of projects) {
    const match = /^project(\d+)$/i.exec(project.name.trim());
    if (!match) continue;
    used.add(Number(match[1]));
  }

  let next = 1;
  while (used.has(next)) next++;
  return `project${next}`;
}

function getUniqueProjectName(projects: StoredProject[], name: string): string {
  const existingNames = new Set(projects.map((p) => p.name));
  let uniqueName = name;
  let counter = 2;
  while (existingNames.has(uniqueName)) {
    uniqueName = `${name} ${counter}`;
    counter++;
  }
  return uniqueName;
}

export function addStoredProject(
  name: string,
  dsl: string,
  multiLayer?: MultiLayerOutput,
  instructionMarkdown?: string,
): StoredProject {
  const projects = readStoredProjects();
  const trimmedName = name.trim();
  const uniqueName = /^project\d+$/i.test(trimmedName)
    ? getNextAutoProjectName(projects)
    : getUniqueProjectName(projects, trimmedName);

  const project: StoredProject = {
    id: `proj-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
    name: uniqueName,
    dsl,
    createdAt: Date.now(),
    ...(multiLayer ? { multiLayer } : {}),
    ...(instructionMarkdown ? { instructionMarkdown } : {}),
  };
  writeStoredProjects([project, ...projects]);
  return project;
}

export function renameStoredProject(id: string, name: string): void {
  const projects = readStoredProjects().map((p) => (p.id === id ? { ...p, name } : p));
  writeStoredProjects(projects);
}

export function getNextProjectName(): string {
  return getNextAutoProjectName(readStoredProjects());
}

export function removeStoredProject(id: string): void {
  const projects = readStoredProjects().filter((p) => p.id !== id);
  writeStoredProjects(projects);
}

export function updateStoredProject(id: string, dsl: string, activeLayer = 'overview'): void {
  const projects = readStoredProjects().map((p) =>
    p.id === id ? applyProjectDsl(p, dsl, activeLayer) : p,
  );
  writeStoredProjects(projects);
}

export function readActiveProjectId(): string | null {
  if (!canUseLocalStorage()) return null;
  return window.localStorage.getItem(ACTIVE_PROJECT_ID_KEY);
}

export function writeActiveProjectId(id: string | null): void {
  if (!canUseLocalStorage()) return;
  if (id === null) {
    window.localStorage.removeItem(ACTIVE_PROJECT_ID_KEY);
  } else {
    window.localStorage.setItem(ACTIVE_PROJECT_ID_KEY, id);
  }
}
